# General information
seed: 1001
__set_seed: !apply:torch.manual_seed [!ref <seed>]
root: !PLACEHOLDER
tokenizers_folder: !ref <root>/tokenizers

# Hyparameters below are dependant on the attack and model used 
# and should be changed at the user's discretion
# -------------------------------------------------------------
# Attack information
snr_pgd: 20
nb_iter_pgd: 100
nested_attack_class: !name:robust_speech.adversarial.attacks.pgd.SNRPGDAttack
  targeted: False
  snr: !ref <snr_pgd>
  nb_iter: !ref <nb_iter_pgd>
nb_iter: 10
eps: 0.01
attack_class: !name:robust_speech.adversarial.attacks.mgaa.ASRMGAA
  targeted: False
  nested_attack_class: !ref <nested_attack_class>
  nb_iter: !ref <nb_iter>
  eps: !ref <eps>

save_audio: False

# Model information
model_name: asr-ctcrnn-librispeech
attack_name: mgaa
target_brain_class: !name:robust_speech.models.ctc.CTCASR
target_brain_hparams_file: !ref model_configs/<model_name>.yaml
model_name2: wav2vec2-base-960h
model_name3: wav2vec2-large-960h
source_brain_class: 
   - !name:robust_speech.models.wav2vec2_fine_tune.W2VASR
   - !name:robust_speech.models.wav2vec2_fine_tune.W2VASR
source_brain_hparams_file: 
   - !ref model_configs/<model_name2>.yaml
   - !ref model_configs/<model_name3>.yaml

# Tokenizer information (compatible with target and source)
pretrained_tokenizer_path: !ref <root>/trainings/<model_name>/tokenizer
tokenizer: !new:speechbrain.dataio.encoder.CTCTextEncoder
# -------------------------------------------------------------

# Pretrainer loading parameters
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
   collect_in: !ref <tokenizers_folder>/<model_name>
   loadables:
      tokenizer: !ref <tokenizer>
   paths:
      tokenizer: !ref <pretrained_tokenizer_path>/tokenizer.ckpt

output_folder: !ref <root>/attacks/transfer/<attack_name>/<model_name>/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>
log: !ref <output_folder>/log.txt
save_audio_path: !ref <output_folder>/save

dataset_prepare_fct: !name:robust_speech.data.librispeech.prepare_librispeech
dataio_prepare_fct: !name:robust_speech.data.librispeech.dataio_prepare

# Data files
data_folder: !ref <root>/data/LibriSpeech # e.g, /localscratch/LibriSpeech
# If RIRS_NOISES dir exists in /localscratch/xxx_corpus/RIRS_NOISES
# then data_folder_rirs should be /localscratch/xxx_corpus
# otherwise the dataset will automatically be downloaded
test_splits: ["test-clean"]
skip_prep: True
ckpt_interval_minutes: 15 # save checkpoint every N min
data_csv_name: test-clean-short
test_csv:
   - !ref <data_folder>/csv/<data_csv_name>.csv
batch_size: 1 # This works for 2x GPUs with 32GB
avoid_if_longer_than: 24.0
sorting: random

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 80

# Decoding parameters (only for text_pipeline)
blank_index: 0
bos_index: 1
eos_index: 2

test_dataloader_opts:
    batch_size: 1

logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <log>
